"""Initial migration.

Revision ID: 20070dbe3f2e
Revises: c0f20ef58369
Create Date: 2023-03-09 13:25:35.741367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20070dbe3f2e'
down_revision = 'c0f20ef58369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_point',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_fk', sa.String(), nullable=True),
    sa.Column('text_body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_fk', sa.String(), nullable=True),
    sa.Column('notification_head', sa.String(), nullable=True),
    sa.Column('notification_body', sa.String(), nullable=True),
    sa.Column('onclick_link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_answer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_fk', sa.String(), nullable=True),
    sa.Column('user_fk', sa.String(), nullable=True),
    sa.Column('given_answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_poll_bet', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('is_poll_bet')

    op.drop_table('poll_answer')
    op.drop_table('notification')
    op.drop_table('list_point')
    # ### end Alembic commands ###
